---
- name: Kafka & Zookeeper
  hosts: kafka
  become: yes

  roles:
    - role: hostname # Warning: change hostname
      hostname_prefix: "kafka-"
    - role: common  # Warning: disable filewalld,selinux,swap
      timezone: "Asia/Shanghai"
    # - role: sshd
    #   sshd_UseDNS: "no"
    #   sshd_PasswordAuthentication: "no"
    - ntpd
    - role: kafka
      zookeeper_memory_percent: 20
      kafka_memory_percent: 40
