---
- name: Install openjdk 8 jre on Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jre
  when:
    - ansible_os_family == "Debian"

- name: Install openjdk 8 jre on RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - java-1.8.0-openjdk
  when:
    - ansible_os_family == "RedHat"
