---
- name: Install openjdk 11 jre on Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jre
  when:
    - ansible_os_family == "Debian"

- name: Install openjdk 11 jre on RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - java-11-openjdk
  when:
    - ansible_os_family == "RedHat"
