---
- name: Install useful package on all platform
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - net-tools
    - tree

- name: Install useful package on Debian
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsutils
  when:
    - ansible_os_family == "Debian"

- name: Install useful package on RedHat
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - bind-utils
  when:
    - ansible_os_family == "RedHat"

- name: Set selinux
  selinux:
    state: disabled
  when:
    - ansible_os_family == "RedHat"

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Stop and disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
