---
- name: Install package on Debian
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-common
  when:
    - ansible_os_family == "Debian"

- name: Install package on RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-utils
  when:
    - ansible_os_family == "RedHat"
