---
- name: Set hostname
  hostname:
    name: "{{ hostname_prefix }}{{ inventory_hostname.replace('.', '-') }}"

- name: Set /etc/hosts
  template:
    src: hosts
    dest: /etc/
    owner: root
    group: root
    mode: '0644'

