---
- name: Install useful package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nc

- name: create data directory
  file:
    path: /data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: add user
  user:
    name: "{{ user }}"
    shell: "/usr/sbin/nologin"
    home: "{{ path }}"
    createhome: no
    system: yes

- name: download package and unarchive
  unarchive:
    src: "{{ base_url }}{{ pkg_name }}.tar.gz"
    dest: "/usr/local"
    remote_src: True
    creates: "/usr/local/{{ pkg_name }}"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: create zoo.cfg
  template:
    src: zoo.cfg
    dest: "/usr/local/{{ pkg_name }}/conf/"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  notify: Restart zookeeper

- name: create log4j.properties
  template:
     src: log4j.properties
     dest: "/usr/local/{{ pkg_name }}/conf/"
     owner: "{{ user }}"
     group: "{{ group }}"
     mode: '0644'
  notify: Restart zookeeper

- name: create symbolic link
  file:
    src: "/usr/local/{{ pkg_name }}"
    dest: "/usr/local/{{ pkg }}"
    state: link
    force: yes

- name: create systemd file
  template:
    src: "{{ pkg }}.service"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemctl
    - Restart zookeeper

- name: create myid
  template:
    src: myid
    dest: "{{ work_dir }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
